ALTER TYPE "EnemyCategory" ADD VALUE 'MUTANT';
ALTER TYPE "EnemyCategory" ADD VALUE 'MECHANICAL';

ALTER TABLE "Game"
ADD COLUMN "bonusLevelCount" INTEGER;

ALTER TABLE "GameLevel"
ADD COLUMN "isBonus" BOOLEAN NOT NULL DEFAULT false;
