ALTER TABLE "Game"
ADD COLUMN "overviewImage" TEXT NOT NULL DEFAULT '',
ADD COLUMN "storyImage" TEXT NOT NULL DEFAULT '',
ADD COLUMN "gameplayImage" TEXT NOT NULL DEFAULT '',
ADD COLUMN "developmentImage" TEXT NOT NULL DEFAULT '',
ADD COLUMN "legacyImage" TEXT NOT NULL DEFAULT '';

ALTER TABLE "GameLevel"
ADD COLUMN "imageUrl" TEXT NOT NULL DEFAULT '';
